name: maven-build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'
      - name: Maven Verify
        run: mvn verify -B
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3