name: maven-release
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish to Maven Central
        run: mvn --batch-mode -P release clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
